name: Build OwO

on:
  push:
    branches: [ OwO ]

jobs:
  build-zig:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zig
        run: |
          ZIG=$(wget --quiet --output-document=- https://ziglang.org/download/index.json | jq --raw-output '.master."x86_64-linux".tarball')
          echo installing $ZIG into ./zig/
          wget --quiet --output-document=- $ZIG | tar Jx
          mv zig-linux-x86_64-* zig
          echo zig version $(./zig/zig version)
          git submodule update --init --recursive
      - name: Build
        run: |
          export PATH=./zig:$PATH
          zig build -Drelease=true
          FILE=web/native/engine.wasm
          test -f "$FILE" || exit 1
      - name: Upload wasm
        uses: actions/upload-artifact@v2
        with:
          name: wasm
          path: web/native
  build-web:
    runs-on: ubuntu-latest
    needs: [build-zig]
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ">= 14.10.0"
      - name: Install dependencies from package.json
        run: |
          cd web
          npm install
      - name: Grab wasm artifact
        uses: actions/download-artifact@v2
        with:
          name: wasm
          path: web/native
      - name: Snowpack build
        run: |
          cd web
          npx snowpack build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: web/build
          
